DROP TABLE IF EXISTS DAILYEXPECTATIONS;

CREATE TABLE DAILYEXPECTATIONS (
ID BIGINT(19) NOT NULL,
DRUMMING INT(2),
WORKING INT(2),
READING INT(2),
WRITING INT(2),
CODING INT(2),
DAY TIMESTAMP(23,10),
EXERCISING INT(2),
DAILYBESTEXPECTATION FLOAT (3),

);